seed: 42

kademlia:
  bit_size: 160
  k:        20
  alpha:    3
  beta:     3

network:
  nodes_count: 200

#   drop_rate:   0

  only_bootstrap_join: true
  bootstrap_count: 5
  bootstrap_conns: 2

# latency:
#   slow_fraction: 0.2
#   fast_ms: 1
#   slow_ms: 10

workload:
  steps: 10
  store: true
  lookups_per_store: 5
  churn:
    phase: before_search    # before_lookup | before_search
    lambda: 20
