seed: 42

kademlia:
  bit_size: 160
  k:        8
  alpha:    5
  beta:     5

network:
  nodes_count: 100

#   drop_rate:   0
#   latency_ms:  0

  only_bootstrap_join: true
  bootstrap_count: 5
  bootstrap_conns: 2



workload:
  steps: 10
  store: true
  lookups_per_store: 20
  churn:
    phase: before_search    # before_lookup | before_search
    lambda: 20