seed: 42

kademlia:
  bit_size: 160
  k:        10
  alpha:    3
  beta:     3

# physical_network:
#   drop_rate:   0
#   latency_ms:  0

network:
  nodes_count: 100
  
  only_bootstrap_join: true
  bootstrap_count: 3
  bootstrap_conns: 2

workload:
  steps: 20
  store: true
  lookups_per_store: 1
