kademlia:
  bit_size: 160
  k:        6
  alpha:    3
  beta:     3

network:
  nodes_count: 100
  drop_rate:   0.1
  latency_ms:  0
  bootstrap:
    nodes_count:       2
    connections_count: 2

workload:
  publications: 100
  