seed: 42

kademlia:
  bit_size: 160
  k:        10
  alpha:    3
  beta:     3

network:
  nodes_count: 100
  # drop_rate:   0
  # latency_ms:  0
  bootstrap:
    nodes_count:       2
    connections_count: 2

workload:
  publications: 80
